#!/usr/bin/env bash
# Resurrect: archive/2026-05-30T13-54-01-841Z/contracts/TRINITY_CAPABILITIES.v0.1.md  →  contracts/TRINITY_CAPABILITIES.v0.1.md
# Auto-generated by t apply-codeicide on 2026-05-30T13:54:01.843Z.
#
# This script restores a file that was reversibly archived by
# t apply-codeicide. ARCHIVE GOVERNANCE, NOT DELETION.
#
# Refuses to overwrite a live file at the destination unless --force.
# This keeps reversibility honest: if someone else recreated the file
# at the original path, restoring would destroy their work.
set -euo pipefail

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *) echo "Unknown arg: $arg"; exit 2 ;;
  esac
done

HERE="$(cd "$(dirname "$0")" && pwd)"
TRINITY_ROOT="$(cd "$HERE/../.." && pwd)"
SRC="$HERE/contracts/TRINITY_CAPABILITIES.v0.1.md"
DST="$TRINITY_ROOT/contracts/TRINITY_CAPABILITIES.v0.1.md"

if [ ! -f "$SRC" ]; then
  echo "RESURRECT.sh: archive source missing: $SRC"
  exit 1
fi

if [ -e "$DST" ] && [ "$FORCE" -ne 1 ]; then
  echo "RESURRECT.sh: destination already exists: contracts/TRINITY_CAPABILITIES.v0.1.md"
  echo "Refusing to overwrite. Re-run with --force if you really mean it."
  echo "  bash $0 --force"
  exit 1
fi

mkdir -p "$(dirname "$DST")"
mv "$SRC" "$DST"
echo "Resurrected: contracts/TRINITY_CAPABILITIES.v0.1.md"
