// Auto-generates x<X>000_mod.ts aggregator per first hex digit of filename.
// Run: deno task gen
//
// Convention: x<4-hex-coordinate>_<snake_handle>.ts
//   - leading 'x' is the language-safe coordinate sigil (Rust mod ids, Python imports, ...)
//   - semantic coordinate stays 4 hex digits; 'x' is filesystem token, not part of meaning
//
// Scans ./src/ for files matching x<hex>{4}_<name>.ts (excluding *.test.ts and aggregators).
// Groups by first hex digit, writes x<X>000_mod.ts that re-exports every file in that bucket.
// Position x<X>000 across all archetypes is reserved for the aggregator.
// Idempotent: same files in → same files out.

const SRC = new URL("./src/", import.meta.url).pathname;

const FILE_RE = /^x([0-9A-Fa-f])[0-9A-Fa-f]{3}_[^.]+\.ts$/;
const AGGREGATOR_RE = /^x[0-9A-Fa-f]000_mod\.ts$/;

async function listSrc(): Promise<string[]> {
  const names: string[] = [];
  for await (const entry of Deno.readDir(SRC)) {
    if (!entry.isFile) continue;
    if (!entry.name.endsWith(".ts")) continue;
    if (entry.name.endsWith(".test.ts")) continue;
    if (AGGREGATOR_RE.test(entry.name)) continue;
    if (!FILE_RE.test(entry.name)) continue;
    names.push(entry.name);
  }
  names.sort();
  return names;
}

function bucketize(names: string[]): Map<string, string[]> {
  const buckets = new Map<string, string[]>();
  for (const name of names) {
    const match = FILE_RE.exec(name);
    if (!match) continue;
    const digit = match[1].toUpperCase();
    const list = buckets.get(digit) ?? [];
    list.push(name);
    buckets.set(digit, list);
  }
  return buckets;
}

function renderMod(digit: string, files: string[]): string {
  const header = `// AUTO-GENERATED by generate_mods.ts — do not edit by hand.\n` +
    `// Bucket: ${digit} (archetype first-digit).\n` +
    `// Files: ${files.length}.\n\n`;
  const exports = files.map((f) => `export * from "./${f}";`).join("\n");
  return header + exports + "\n";
}

async function existingMods(): Promise<Set<string>> {
  const seen = new Set<string>();
  for await (const entry of Deno.readDir(SRC)) {
    if (entry.isFile && AGGREGATOR_RE.test(entry.name)) {
      seen.add(entry.name);
    }
  }
  return seen;
}

async function main() {
  const names = await listSrc();
  const buckets = bucketize(names);
  const desired = new Set<string>();
  let changed = 0;

  for (const [digit, files] of buckets) {
    const modName = `x${digit}000_mod.ts`;
    desired.add(modName);
    const content = renderMod(digit, files);
    const path = `${SRC}${modName}`;
    let prior = "";
    try {
      prior = await Deno.readTextFile(path);
    } catch (_) {
      // didn't exist
    }
    if (prior !== content) {
      await Deno.writeTextFile(path, content);
      console.log(`[write] ${modName} (${files.length} files)`);
      changed++;
    }
  }

  // Remove stale mod_X.ts that have no source files anymore.
  for (const mod of await existingMods()) {
    if (!desired.has(mod)) {
      await Deno.remove(`${SRC}${mod}`);
      console.log(`[remove] ${mod} (no source files)`);
      changed++;
    }
  }

  console.log(`done. ${changed} change(s). buckets: ${[...desired].sort().join(", ")}`);
}

if (import.meta.main) {
  await main();
}
