// gen.ts — bucket-state generator (probe v0)
//
// Walks ./src/ for files matching x<bucket><sub-3>_<handle>.ts, parses
// header comments for `intent / maturity / horizon` fields, and renders
// xN888_state.myc.md (per-bucket) + x8888_agents.myc.md (substrate-level
// federation pointer).
//
// Self-contained: works against probe fixture in ./src/ only. Does NOT
// touch trinity's real src/. Output goes to ./output/.
//
// Run: deno run --config=probe.jsonc -A gen.ts [--bucket=6]

import { dirname, fromFileUrl, join } from "https://deno.land/std@0.224.0/path/mod.ts";

const HERE = dirname(fromFileUrl(import.meta.url));
const SRC = join(HERE, "src");
const OUT = join(HERE, "output");

const FILENAME_RE = /^x([0-9A-Fa-f])([0-9A-Fa-f]{3})_([^.]+)\.ts$/;
const HEADER_RE = /^\/\/\s*(\w+):\s*(.+?)\s*$/;

const KNOWN_HEADER_FIELDS = new Set([
  "intent",
  "maturity",
  "horizon",
  "position",
  "hex_dipole",
  "placement_policy",
]);

type Maturity = "draft" | "active" | "frozen" | "archived";

interface OrganMeta {
  filename: string;
  coordinate: string; // "6020"
  bucket: string; // "6"
  sub: string; // "020"
  handle: string;
  intent?: string;
  maturity?: Maturity;
  horizon?: string;
  position?: string;
  hex_dipole?: string;
  placement_policy?: string;
}

function parseHeader(content: string): Map<string, string> {
  const fields = new Map<string, string>();
  const lines = content.split("\n").slice(0, 30);
  for (const line of lines) {
    const m = HEADER_RE.exec(line);
    if (!m) continue;
    const [, key, val] = m;
    if (!KNOWN_HEADER_FIELDS.has(key)) continue;
    if (!fields.has(key)) fields.set(key, val); // first wins
  }
  return fields;
}

async function scanSrc(): Promise<OrganMeta[]> {
  const organs: OrganMeta[] = [];
  for await (const entry of Deno.readDir(SRC)) {
    if (!entry.isFile) continue;
    const m = FILENAME_RE.exec(entry.name);
    if (!m) continue;
    const [, bucket, sub, handle] = m;
    const content = await Deno.readTextFile(join(SRC, entry.name));
    const fields = parseHeader(content);
    organs.push({
      filename: entry.name,
      coordinate: (bucket + sub).toUpperCase(),
      bucket: bucket.toUpperCase(),
      sub: sub.toUpperCase(),
      handle,
      intent: fields.get("intent"),
      maturity: fields.get("maturity") as Maturity | undefined,
      horizon: fields.get("horizon"),
      position: fields.get("position"),
      hex_dipole: fields.get("hex_dipole"),
      placement_policy: fields.get("placement_policy"),
    });
  }
  return organs.sort((a, b) => a.coordinate.localeCompare(b.coordinate));
}

function groupByBucket(organs: OrganMeta[]): Map<string, OrganMeta[]> {
  const buckets = new Map<string, OrganMeta[]>();
  for (const o of organs) {
    const list = buckets.get(o.bucket) ?? [];
    list.push(o);
    buckets.set(o.bucket, list);
  }
  return buckets;
}

function renderBucketState(bucket: string, organs: OrganMeta[], now: string): string {
  const active = organs.filter((o) => o.maturity === "active");
  const frozen = organs.filter((o) => o.maturity === "frozen");
  const draft = organs.filter((o) => o.maturity === "draft");
  const archived = organs.filter((o) => o.maturity === "archived");
  const unknown = organs.filter((o) => !o.maturity);

  const lines: string[] = [];
  lines.push(`<!-- AUTO-GENERATED by probes/agents-gen-v0/gen.ts — do not edit by hand. -->`);
  lines.push(`<!-- generated_at: ${now} -->`);
  lines.push(`<!-- bucket: ${bucket}   organs: ${organs.length} -->`);
  lines.push(``);
  lines.push(`# Bucket ${bucket} state`);
  lines.push(``);
  lines.push(
    `${organs.length} organs in bucket ${bucket} — ` +
      `${active.length} active, ${frozen.length} frozen, ${draft.length} draft, ${archived.length} archived` +
      (unknown.length > 0 ? `, ${unknown.length} unknown-maturity` : "") +
      `.`,
  );
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // є (current state, lower half x?880..x?887)
  lines.push(`## є — current state  (sub-positions ${bucket}880..${bucket}887)`);
  lines.push(``);

  if (active.length > 0) {
    lines.push(`### ${bucket}884 — foundation (active organs)`);
    lines.push(``);
    for (const o of active) {
      lines.push(`- **x${o.coordinate}_${o.handle}** — ${o.intent ?? "(no intent declared)"}`);
    }
    lines.push(``);
  }

  if (frozen.length > 0) {
    lines.push(`### ${bucket}887 — sealed (frozen organs)`);
    lines.push(``);
    for (const o of frozen) {
      lines.push(`- **x${o.coordinate}_${o.handle}** — ${o.intent ?? "(no intent declared)"}`);
    }
    lines.push(``);
  }

  if (unknown.length > 0) {
    lines.push(`### ${bucket}880 — unclassified (no maturity declared)`);
    lines.push(``);
    for (const o of unknown) {
      lines.push(`- **x${o.coordinate}_${o.handle}** — ${o.intent ?? "(no intent declared)"}`);
    }
    lines.push(``);
  }

  if (archived.length > 0) {
    lines.push(`### ${bucket}880 — origin (archived organs)`);
    lines.push(``);
    for (const o of archived) {
      lines.push(`- **x${o.coordinate}_${o.handle}** — ${o.intent ?? "(archived)"}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);

  // буде (intent vector, upper half x?889..x?88F)
  lines.push(`## буде — intent vector  (sub-positions ${bucket}889..${bucket}88F)`);
  lines.push(``);

  if (draft.length > 0) {
    lines.push(`### ${bucket}889 — next step (draft organs in flight)`);
    lines.push(``);
    for (const o of draft) {
      const horizon = o.horizon ? ` — horizon: ${o.horizon}` : "";
      lines.push(`- **x${o.coordinate}_${o.handle}** — ${o.intent ?? "(no intent declared)"}${horizon}`);
    }
    lines.push(``);
  }

  // Collect all horizons (regardless of maturity) into frontier synthesis
  const horizons = organs.filter((o) => o.horizon).map((o) => ({ coord: o.coordinate, horizon: o.horizon! }));
  if (horizons.length > 0) {
    lines.push(`### ${bucket}88F — frontier (horizon synthesis from all organs)`);
    lines.push(``);
    for (const { coord, horizon } of horizons) {
      lines.push(`- *from x${coord}:* ${horizon}`);
    }
    lines.push(``);
  }

  if (draft.length === 0 && horizons.length === 0) {
    lines.push(`### ${bucket}889..${bucket}88F — empty`);
    lines.push(`No draft organs and no declared horizons. Bucket ${bucket} appears settled.`);
    lines.push(``);
  }

  return lines.join("\n");
}

function renderSubstrateAgents(buckets: Map<string, OrganMeta[]>, now: string): string {
  const lines: string[] = [];
  lines.push(`<!-- AUTO-GENERATED by probes/agents-gen-v0/gen.ts — do not edit by hand. -->`);
  lines.push(`<!-- generated_at: ${now} -->`);
  lines.push(``);
  lines.push(`# Substrate state (federation index)`);
  lines.push(``);
  lines.push(`Total organs: ${[...buckets.values()].flat().length} across ${buckets.size} buckets.`);
  lines.push(``);
  lines.push(`## Local buckets`);
  lines.push(``);
  for (const [bucket, organs] of [...buckets.entries()].sort()) {
    const active = organs.filter((o) => o.maturity === "active").length;
    const draft = organs.filter((o) => o.maturity === "draft").length;
    lines.push(`- **bucket ${bucket}** — ${organs.length} organs (${active} active, ${draft} draft) → see [x${bucket}888_state.myc.md](./x${bucket}888_state.myc.md)`);
  }
  lines.push(``);
  lines.push(`## Federated substrates (pointers — substrates self-describe)`);
  lines.push(``);
  lines.push(`- → liquid/src/x8888_agents.myc.md (regenerate inside liquid)`);
  lines.push(`- → omega/src/x8888_agents.myc.md (regenerate inside omega)`);
  lines.push(`- → myc/src/x8888_agents.myc.md (regenerate inside myc)`);
  lines.push(``);
  lines.push(`## How to use this file`);
  lines.push(``);
  lines.push(`Fresh model: read this first, then drill into bucket-specific xN888_state.myc.md as needed.`);
  lines.push(`AGENTS.md (palimpsest dialog) — separate concern, complementary, not replaced.`);
  lines.push(`This file is regenerated by \`t agents\` (or probe \`gen.ts\` while in trial).`);
  return lines.join("\n");
}

async function main() {
  await Deno.mkdir(OUT, { recursive: true });

  const organs = await scanSrc();
  const buckets = groupByBucket(organs);
  const now = new Date().toISOString();

  let written = 0;
  for (const [bucket, bucketOrgans] of buckets) {
    const path = join(OUT, `x${bucket}888_state.myc.md`);
    const content = renderBucketState(bucket, bucketOrgans, now);
    await Deno.writeTextFile(path, content + "\n");
    console.log(`[write] x${bucket}888_state.myc.md (${bucketOrgans.length} organs)`);
    written++;
  }

  const agentsPath = join(OUT, "x8888_agents.myc.md");
  const agentsContent = renderSubstrateAgents(buckets, now);
  await Deno.writeTextFile(agentsPath, agentsContent + "\n");
  console.log(`[write] x8888_agents.myc.md (${buckets.size} buckets indexed)`);
  written++;

  console.log(`done. ${written} files written to output/.`);
}

if (import.meta.main) {
  await main();
}
