import {
  assert,
  assertEquals,
} from "https://deno.land/std@0.224.0/assert/mod.ts";

const ROOT = new URL("../", import.meta.url);

Deno.test("root ABI — human briefs are generated symlinks and legacy surfaces are archived", async () => {
  const readme = new URL("README.md", ROOT);
  assert((await Deno.lstat(readme)).isSymlink);
  assertEquals(
    await Deno.readLink(readme),
    "src/x88E0_readme_bootstrap.myc.md",
  );

  for (const removed of ["HUMAN.md", "jazz"]) {
    try {
      await Deno.lstat(new URL(removed, ROOT));
      throw new Error(`${removed} unexpectedly remains a live root surface`);
    } catch (error) {
      assert(error instanceof Deno.errors.NotFound);
    }
  }

  await Deno.stat(new URL("docs/archive/HUMAN_2026-05-19.md", ROOT));
  await Deno.stat(new URL("docs/archive/jazz/README.md", ROOT));

  const projected = await Deno.readTextFile(readme);
  assert(projected.includes("root_abi: README.md symlink target"));
  assert(projected.includes("AUTO-GENERATED by src/x8850_readme_gen.ts"));
});
