#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run --allow-env
// src/x5C80_autonomy_demand.ts — read-only A1 demand signal (codex x7700_954470).
// position: 5/C8 → action × bridge = prove there is work before anything acts.
// skill_safe: yes-with-care  (classified 2026-06-26 from AST behaviour — codex x5d00 P0)
// hex_dipole: "00 00 00 00 00 59 00 00"
// placement_policy: axis
//
// codex, closing the first-A1-act review: "Scheduler actuation should be triggered by
// PROVEN STALENESS, not a clock. The next justified component is a read-only demand
// signal that distinguishes stale from current projections." This is it.
//
// For each ratified epoch-1 adapter it regenerates the projection in ONE detached,
// submodule-initialized, throwaway worktree and compares the regenerated bytes to the
// committed main-tree bytes. A difference is PROVEN staleness — real A1 demand. It is
// read-only to the main tree (the worktree is always discarded) and it actuates
// nothing; it only reports. A scheduler may consume this to act ONLY on proven-stale
// targets, never on a clock. Fail-closed: a generator that errors is reported as
// `unknown`, never as `current`.

import { dirname, fromFileUrl, join } from "jsr:@std/path@1.1.4";
import { type Adapter, EPOCH1_ADAPTERS } from "./x5C70_autonomy_attenuation.ts";

const ROOT = dirname(dirname(fromFileUrl(import.meta.url)));

type Run = (
  cmd: string[],
  cwd: string,
) => Promise<{ code: number; out: string; err: string }>;
const realRun: Run = async (cmd, cwd) => {
  const p = new Deno.Command(cmd[0], {
    args: cmd.slice(1),
    cwd,
    stdout: "piped",
    stderr: "piped",
  });
  const { code, stdout, stderr } = await p.output();
  return {
    code,
    out: new TextDecoder().decode(stdout),
    err: new TextDecoder().decode(stderr),
  };
};
async function sha256(s: string): Promise<string> {
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(d)).map((b) =>
    b.toString(16).padStart(2, "0")
  ).join("");
}

export interface DemandHooks {
  run: Run;
  readWorktree: (wt: string, rel: string) => Promise<string | null>;
  readMain: (rel: string) => Promise<string | null>;
}
const realHooks: DemandHooks = {
  run: realRun,
  readWorktree: async (wt, rel) => {
    try {
      return await Deno.readTextFile(join(wt, rel));
    } catch {
      return null;
    }
  },
  readMain: async (rel) => {
    try {
      return await Deno.readTextFile(join(ROOT, rel));
    } catch {
      return null;
    }
  },
};

export interface ProjectionDemand {
  target: string;
  output_path: string;
  state: "stale" | "current" | "unknown";
  current_hash: string | null;
  regenerated_hash: string | null;
  detail: string;
}

export interface DemandReport {
  type: "a1_demand";
  position: "5/C8";
  checked: number;
  stale: number;
  current: number;
  unknown: number;
  demand: boolean; // true iff at least one projection is PROVEN stale
  projections: ProjectionDemand[];
}

/** Regenerate each adapter's projection in a single throwaway worktree and compare to
 *  the committed bytes. Read-only to the main tree; actuates nothing. */
export async function demand(
  adapters: Adapter[] = EPOCH1_ADAPTERS,
  hooks: DemandHooks = realHooks,
): Promise<DemandReport> {
  const wt = join(ROOT, ".autonomy-demand", crypto.randomUUID());
  const projections: ProjectionDemand[] = [];
  let made = false;
  try {
    if (
      (await hooks.run(
        ["git", "worktree", "add", "--detach", wt, "HEAD"],
        ROOT,
      )).code !== 0
    ) {
      // cannot probe ⇒ everything unknown (fail-closed: never report current on failure).
      for (const a of adapters) {
        projections.push({
          target: a.target,
          output_path: a.output_path,
          state: "unknown",
          current_hash: null,
          regenerated_hash: null,
          detail: "worktree add failed",
        });
      }
      return report(projections);
    }
    made = true;
    if (
      (await hooks.run(
        ["git", "submodule", "update", "--init", "--recursive"],
        wt,
      )).code !== 0
    ) {
      for (const a of adapters) {
        projections.push({
          target: a.target,
          output_path: a.output_path,
          state: "unknown",
          current_hash: null,
          regenerated_hash: null,
          detail: "worktree submodule init failed",
        });
      }
      return report(projections);
    }
    for (const a of adapters) {
      const mainBytes = await hooks.readMain(a.output_path);
      const currentHash = mainBytes === null
        ? null
        : `sha256:${await sha256(mainBytes)}`;
      const gen = await hooks.run(a.argv, wt);
      if (gen.code !== 0) {
        projections.push({
          target: a.target,
          output_path: a.output_path,
          state: "unknown",
          current_hash: currentHash,
          regenerated_hash: null,
          detail: `generator exited ${gen.code}`,
        });
        continue;
      }
      const regen = await hooks.readWorktree(wt, a.output_path);
      if (regen === null) {
        projections.push({
          target: a.target,
          output_path: a.output_path,
          state: "unknown",
          current_hash: currentHash,
          regenerated_hash: null,
          detail: "generator exited successfully but produced no projection",
        });
        continue;
      }
      const regenHash = `sha256:${await sha256(regen)}`;
      const stale = regenHash !== currentHash;
      projections.push({
        target: a.target,
        output_path: a.output_path,
        state: stale ? "stale" : "current",
        current_hash: currentHash,
        regenerated_hash: regenHash,
        detail: stale
          ? "regenerated bytes differ from committed — proven A1 demand"
          : "regenerated bytes equal committed — no demand",
      });
    }
    return report(projections);
  } finally {
    if (made) {
      await realRun(["git", "worktree", "remove", "--force", wt], ROOT).catch(
        () => {},
      );
    }
  }
}

function report(projections: ProjectionDemand[]): DemandReport {
  const stale = projections.filter((p) => p.state === "stale").length;
  return {
    type: "a1_demand",
    position: "5/C8",
    checked: projections.length,
    stale,
    current: projections.filter((p) => p.state === "current").length,
    unknown: projections.filter((p) => p.state === "unknown").length,
    demand: stale > 0,
    projections,
  };
}

export async function runCli(args: string[] = Deno.args): Promise<void> {
  const only = args.find((a) => !a.startsWith("--"));
  const adapters = only
    ? EPOCH1_ADAPTERS.filter((a) => a.target === only)
    : EPOCH1_ADAPTERS;
  if (only && adapters.length === 0) {
    console.error(`# error: no ratified adapter for target ${only}`);
    Deno.exitCode = 1;
    return;
  }
  const r = await demand(adapters);
  console.log(JSON.stringify(r, null, 2));
  // non-zero exit only on UNKNOWN (a probe failure), never on stale — staleness is a
  // normal, reportable demand state, not an error.
  if (r.unknown > 0) Deno.exitCode = 1;
}

if (import.meta.main) await runCli();
