#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run
// src/x8700_network.ts — the network for people: a generated markdown projection
// position: 8/7 → projection(8) × completion(7) = a finished, human-readable
//   projection of the live network (the "FQDN network for people" front step)
// hex_dipole: "59 00 00 00 00 00 00 33"
//   void_infinity+0.70 (PRIMARY: projection/cache pole; bucket 8 MATCH on axis 0)
//   completion_frontier+0.40 (emits a finished doc at the frontier of "for people")
// placement_policy: axis
// maturity: active
// horizon: none (v0 renders atlas + lineage; richer per-substrate views deferred)
// skill_tag: network
// skill_safe: yes-with-care
//   writes one tracked projection (src/x8788_network.myc.md) — a benign,
//   idempotent regen, maintained like every other stable projection.
//
// intent: a person who is NOT in the terminal cannot read `t resolve-fqdn atlas`.
//   This renders the same live data (atlas = shape, lineage = becoming) into a
//   markdown projection that renders on GitHub — the living-README pattern: a
//   read-only projection of ledger state, regenerated, never hand-edited. Composes
//   the resolver's own aggregates via callT (no import; bucket 8 → bucket 2).
//
// Usage:
//   t network            regenerate the projection (with a generated_at stamp)
//   t network --stable    deterministic (no wall-clock) — the CI/daemon form
//   t network --json      machine-readable receipt (manifest_hash)

import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.224.0/path/mod.ts";
// bucket-0 library — canonicalizes generated output to `deno fmt` form, so the
// regen sweep and `deno fmt --check` agree (the same helper every gen uses).
import { formatGeneratedFile } from "./x0012_generated_format.ts";

const HERE = dirname(fromFileUrl(import.meta.url));
const DISPATCH = join(HERE, "x0100_dispatch.ts");
const OUT = join(HERE, "x8788_network.myc.md");

interface AtlasMember {
  member: string;
  nodes: number;
  chords: number;
}
interface Hub {
  stem: string;
  in: number;
}
interface RecentEntry {
  when: string;
  voice: string;
  slug: string;
  closes: string[];
}
interface Atlas {
  total_nodes: number;
  members: AtlasMember[];
  by_kind: Record<string, number>;
  top_cited: Hub[];
  recent: RecentEntry[];
  recent_total: number;
  index?: { source_hash?: string };
}
interface Arc {
  proposal: string;
  resolved: boolean;
  proposal_voice: string | null;
  depth: number;
  span_blocks: number | null;
  voices: string[];
}
interface Lineage {
  total_closed: number;
  total_receipts: number;
  arcs: Arc[];
}

async function callJson(args: string[]): Promise<unknown> {
  const p = new Deno.Command("deno", {
    args: ["run", "-A", DISPATCH, ...args],
    stdout: "piped",
    stderr: "piped",
  });
  const o = await p.output();
  const out = new TextDecoder().decode(o.stdout);
  // dispatch prints a `# verb → pos` header before the JSON payload
  const i = out.split("\n").findIndex((l) => l.trimStart().startsWith("{"));
  if (i === -1) throw new Error(`no JSON from: ${args.join(" ")}`);
  return JSON.parse(out.split("\n").slice(i).join("\n"));
}

export function networkResolverArgs(
  stable: boolean,
  view: "atlas" | "lineage",
): string[] {
  return [
    "resolve-fqdn",
    view,
    ...(view === "lineage" ? ["--limit=12"] : []),
    ...(stable ? ["--no-cache"] : []),
    "--json",
  ];
}

async function sha256Hex(s: string): Promise<string> {
  const buf = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(s),
  );
  return Array.from(new Uint8Array(buf)).map((b) =>
    b.toString(16).padStart(2, "0")
  ).join("");
}

/** Render the projection. Pure given (atlas, lineage). `generated_at` is null in
 *  --stable mode so the output is byte-deterministic (CI diffs it twice). */
export function renderNetwork(
  atlas: Atlas,
  lineage: Lineage,
  meta: { generated_at: string | null; manifest_hash: string },
): string {
  const L: string[] = [];
  L.push(
    "<!-- AUTO-GENERATED by src/x8700_network.ts — do not edit by hand. -->",
  );
  if (meta.generated_at) L.push(`<!-- generated_at: ${meta.generated_at} -->`);
  L.push(`<!-- source_manifest_hash: ${meta.manifest_hash} -->`);
  L.push("");
  L.push(`# The FQDN network`);
  L.push("");
  L.push(
    `**${atlas.total_nodes} nodes across ${atlas.members.length} substrates.** ` +
      `A federation of living substrates: every organ sits at a fixed hex ` +
      `coordinate (by role, not by content), every chord is a signed provenance ` +
      `event, and every edge — what a node hears, closes, references, imports — ` +
      `is git- and crypto-checkable. Nothing here is hand-placed; it is grown, ` +
      `signed, and projected. This page is itself a projection — regenerated from ` +
      `the ledger, never edited.`,
  );
  L.push("");

  L.push("## Where you are — the shape");
  L.push("");
  L.push("| substrate | nodes | chords |");
  L.push("| --------- | ----: | -----: |");
  for (const m of atlas.members) {
    L.push(`| ${m.member} | ${m.nodes} | ${m.chords} |`);
  }
  L.push("");
  const kinds = Object.entries(atlas.by_kind).sort((a, b) => b[1] - a[1]);
  L.push(`Made of: ${kinds.map(([k, n]) => `${n} ${k}`).join(", ")}.`);
  L.push("");
  L.push("**Most-cited — what the network leans on:**");
  L.push("");
  for (const h of atlas.top_cited) L.push(`- \`${h.stem}\` — cited ${h.in}×`);
  L.push("");

  L.push("## How it came to be — the becoming");
  L.push("");
  L.push(
    `${lineage.total_closed} proposals closed by ${lineage.total_receipts} ` +
      `receipt-chords. Each arc below is a proposal and the phases it took to ` +
      `close (derived from the signed \`closes\` edges) — the major efforts that ` +
      `shaped the network:`,
  );
  L.push("");
  for (const a of lineage.arcs) {
    const phases = a.depth === 1 ? "1 phase" : `${a.depth} phases`;
    const span = a.span_blocks !== null ? `, ~${a.span_blocks} blocks` : "";
    const by = a.proposal_voice ? `, proposed by ${a.proposal_voice}` : "";
    const tag = a.resolved ? "" : " *(logical)*";
    L.push(
      `- **${a.proposal}**${tag} — ${phases}${span}; closed by ${
        a.voices.join(", ")
      }${by}`,
    );
  }
  L.push("");

  L.push("## Step in");
  L.push("");
  L.push(
    "This page is a snapshot. The live network is navigable from the CLI:",
  );
  L.push("");
  L.push("- `t resolve-fqdn atlas` — this shape, live");
  L.push("- `t resolve-fqdn lineage` — these arcs, in full");
  L.push("- `t resolve-fqdn recent` — the timeline of recent activity");
  L.push("- `t resolve-fqdn search <term>` — find a node by name");
  L.push("- `t resolve-fqdn show <name>` — read one node's content");
  L.push("- `t roadmap` — where the network is going");
  L.push("");
  return L.join("\n") + "\n";
}

async function main(argv: string[]) {
  const stable = argv.includes("--stable");
  const wantJson = argv.includes("--json");

  // Stable projections are a function of repository inputs, never of the
  // gitignored resolver cache present on one machine. A fresh checkout and a
  // long-lived worktree must therefore select the same live-built artifact.
  const atlas = await callJson(networkResolverArgs(stable, "atlas")) as Atlas;
  const lineage = await callJson(
    networkResolverArgs(stable, "lineage"),
  ) as Lineage;

  // Deterministic basis: the STRUCTURAL data actually rendered — NOT the index
  // source_hash. The resolver indexes this projection itself, so hashing the index
  // would feed our own output back in: regen → content changes → index hash changes
  // → never converges → CI's `git diff --exit-code` reds. The rendered fields
  // (counts, members, hubs, arcs) are stable across a self-regen (this doc cites
  // nothing and nothing cites it), so the basis is a fixed point.
  const basis = await sha256Hex(JSON.stringify({
    total_nodes: atlas.total_nodes,
    members: atlas.members,
    by_kind: atlas.by_kind,
    top_cited: atlas.top_cited,
    total_closed: lineage.total_closed,
    total_receipts: lineage.total_receipts,
    arcs: lineage.arcs,
  }));
  const manifest_hash = `sha256:${basis}`;
  const generated_at = stable ? null : new Date().toISOString();

  const md = renderNetwork(atlas, lineage, { generated_at, manifest_hash });
  await Deno.writeTextFile(OUT, md);
  await formatGeneratedFile(OUT); // canonicalize to `deno fmt` form (no fmt↔regen oscillation)

  if (wantJson) {
    console.log(JSON.stringify(
      {
        type: "network",
        position: "8/7",
        action: "generate",
        stable,
        written: 1,
        output: "src/x8788_network.myc.md",
        total_nodes: atlas.total_nodes,
        substrates: atlas.members.length,
        arcs: lineage.arcs.length,
        manifest_hash,
      },
      null,
      2,
    ));
  } else {
    console.log(`# network → 8/7`);
    console.log(
      `[write] src/x8788_network.myc.md (${atlas.total_nodes} nodes, ${atlas.members.length} substrates, ${lineage.arcs.length} arcs)`,
    );
    console.log(
      `done. 1 file. manifest_hash=${manifest_hash}${
        stable ? " (stable)" : ""
      }`,
    );
  }
}

if (import.meta.main) {
  await main(Deno.args);
}
