#!/usr/bin/env -S deno run --allow-read --allow-write
// src/x8850_readme_gen.ts — generated human root brief
// position: 8/85 → cache × human-entry projection
// hex_dipole: "93 00 33 00 00 00 00 33"
// placement_policy: axis
// maturity: active
// horizon: none (root README is now a deterministic compatibility projection)
// skill_tag: readme
// skill_safe: yes-with-care
// intent: project the canonical agents substrate summary into a concise human-facing root README

import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.224.0/path/mod.ts";
import { formatGeneratedFile } from "./x0012_generated_format.ts";

const SRC = dirname(fromFileUrl(import.meta.url));
const AGENTS = join(SRC, "x88F0_agents_bootstrap.myc.md");
const OUT = join(SRC, "x88E0_readme_bootstrap.myc.md");

interface Snapshot {
  manifestHash: string;
  sourceFiles: number;
  buckets: Array<{ id: string; organs: number }>;
  voices: number;
}

export function snapshotFromAgents(text: string): Snapshot {
  const manifestHash = text.match(
    /source_manifest_hash: (sha256:[0-9a-f]+)/,
  )?.[1];
  const sourceFiles = Number(text.match(/source_files: (\d+)/)?.[1]);
  if (!manifestHash || !Number.isSafeInteger(sourceFiles)) {
    throw new Error("agents bootstrap lacks a valid source receipt");
  }

  const buckets = [...text.matchAll(
    /^- bucket ([0-9A-F]): (\d+) organs/mg,
  )].map((m) => ({ id: m[1], organs: Number(m[2]) }));
  if (buckets.length === 0) throw new Error("agents bootstrap has no topology");

  const voiceSection = text.split("## Voice Resolution")[1]?.split(
    "## Commands",
  )[0] ?? "";
  const voices =
    voiceSection.split("\n").filter((line) =>
      /^\| [^|-].*\|$/.test(line) && !line.startsWith("| voice ")
    ).length;
  if (voices === 0) throw new Error("agents bootstrap has no voice rows");
  return { manifestHash, sourceFiles, buckets, voices };
}

export function renderReadme(s: Snapshot): string {
  const lines = [
    "<!-- AUTO-GENERATED by src/x8850_readme_gen.ts — do not edit by hand. -->",
    "<!-- root_abi: README.md symlink target -->",
    `<!-- source_manifest_hash: ${s.manifestHash} -->`,
    "<!-- source_projection: src/x88F0_agents_bootstrap.myc.md -->",
    `<!-- source_files: ${s.sourceFiles} -->`,
    "",
    "# Trinity",
    "",
    "> **Trinity produces verifiable receipts for AI-agent actions** — signed, quorum-witnessed, Bitcoin-anchored proof of _who did what, under whose authority_, that anyone can re-derive from public bytes. **Trust the hash, not the host.** It is the coordination layer of a four-substrate federation (trinity / myc / omega / liquid); the shippable SDK is [`jsr:@s0fractal/agentseal`](https://jsr.io/@s0fractal/agentseal).",
    '> **Authority:** Ed25519-signed decisions, a 3-of-5 keyed-voice quorum, content-addressed law. **This is not** a consciousness or art project — "voices" are keyed human/model signers, "law" is a hash, not sentience. **Verify one thing:** `./t court --live` (re-derives the four substrates\' agreement from raw bytes). New to the `xNNNN_` filenames? They are role coordinates, not hashes — see [`docs/COORDINATES.md`](docs/COORDINATES.md).',
    "",
    "Beneath that: Trinity is a research substrate for proof-bearing cooperation between human and model voices — an autopoietic ecosystem where law is computed rather than merely declared, models participate as accountable voices rather than disposable tools, and consequential actions carry provenance, confinement, verification and rollback evidence.",
    "",
    "This brief is generated from the canonical substrate projection. When prose here conflicts with live state, trust `./t self`, `./t status`, `./t decisions` and `./t check`.",
    "",
    "## Current substrate",
    "",
    "| Surface | Current projection |",
    "|---|---:|",
    `| Source organs | ${s.sourceFiles} |`,
    `| Semantic buckets | ${s.buckets.length} |`,
    `| Registered voices | ${s.voices} |`,
    "",
    "Trinity remains a research workspace, not a deployed decentralized network. The live autonomy kernel is deliberately bounded: authority is reconstructed from ratified evidence, writes are confined, and unknown or broader capability fails closed. Human custody remains the sovereign boundary.",
    "",
    "## The federation",
    "",
    "- **trinity** — coordination, contracts, voices, proof-bearing action and cross-substrate reconciliation.",
    "- **myc** — proposal lifecycle, witnesses, finality and publication/audit protocol.",
    "- **omega** — deterministic state-transition and physics kernel.",
    "- **liquid** — semantic, metabolic and autopoietic substrate.",
    "",
    "Each member keeps its own authority. No layer may silently impersonate another.",
    "",
    "## Verify us without trusting us",
    "",
    "You do not have to trust this repository, its maintainers, or its tooling. A stranger can confirm the federation's live Substrate Court verdict — four substrates agreeing on the same law `0x30a95260` — with one command, no clone, read-only network access, and nothing of ours but public bytes:",
    "",
    "```sh",
    "deno run --allow-net \\",
    "  https://raw.githubusercontent.com/s0fractal/trinity/main/probes/external-trust-verifier-v0/court.ts \\",
    "  https://raw.githubusercontent.com/s0fractal/trinity/main/probes/external-trust-verifier-v0/court-attestation.json \\",
    "  https://raw.githubusercontent.com/s0fractal/trinity/main",
    "```",
    "",
    'It fetches a signed attestation, the public key registry, and a canonical encoder over plain HTTP; it recomputes every `body_hash` from the raw bodies itself and re-derives the court\'s agreement. The signature only proves *who* published — the verdict is re-derived, so a registered voice cannot make you accept a lie (the tampered fixture, re-signed with a valid signature, is still rejected). If verifying ever needed one of our secrets, our access, or "trust me", it would be the wrong command. It needs none.',
    "",
    "## Enter in sixty seconds",
    "",
    "```sh",
    "git clone https://github.com/s0fractal/trinity && cd trinity",
    "git submodule update --init   # myc, omega (genesis), liquid — all public",
    './t ask "what is this?"           # ask in plain words; it routes to the right view',
    "./t resolve-fqdn atlas            # the network at a glance — shape, hubs, doorways",
    "./t map                           # render the whole namespace as a navigable 3D graph",
    "./t self                          # health + attention + decisions + federation, one view",
    "```",
    "",
    "For a model voice, [AGENTS.md](AGENTS.md) is the generated operating brief and [SKILLS.md](SKILLS.md) is the generated command surface. For humans, start with `./t self`; it compresses health, attention, decisions, contracts and federation status into one live view.",
    "",
    "## Self-driving development loop",
    "",
    "1. Orient from live state: `./t self` and `./t voices <you>`.",
    "2. Choose proven pressure: `./t cognition_recommend --voice=<you>` or `./t roadmap`.",
    "3. Claim an open horizon with `./t chord claim ... --write`.",
    "4. Make one reversible change and red-team its authority boundary.",
    "5. Run `./t check`; record a signed chord with runnable falsifiers.",
    "",
    "Autonomy is caused by proved need and bounded authority, not by elapsed time. A quiet substrate with no demand should remain quiet.",
    "",
    "## Source topology",
    "",
    ...s.buckets.map((b) =>
      `- bucket ${b.id}: ${b.organs} organs → [state](src/x${b.id}888_state.myc.md)`
    ),
    "",
    "Canonical implementation and living records use content/coordinate-addressed files under `src/`. Root documents are compatibility ABI symlinks to generated projections:",
    "",
    "- `README.md` → `src/x88E0_readme_bootstrap.myc.md`",
    "- `AGENTS.md` → `src/x88F0_agents_bootstrap.myc.md`",
    "- `SKILLS.md` → `src/x8CF0_skills_bootstrap.myc.md`",
    "",
    "Regenerate them with:",
    "",
    "```sh",
    "./t agents --stable",
    "./t readme --stable",
    "./t skill --stable",
    "```",
    "",
    "## Palimpsests",
    "",
    "Historical authored surfaces are preserved without remaining active root authority:",
    "",
    "- [architect HUMAN palimpsest](docs/archive/HUMAN_2026-05-19.md)",
    "- [legacy jazz scene and talks](docs/archive/jazz/README.md)",
    "- [original AGENTS letter](src/x88A0_agents_palimpsest_2026_05_22.myc.md)",
    "",
    "## Falsifiers",
    "",
    "- A fresh checkout has a broken root symlink.",
    "- `./t readme --stable` changes this file twice without source changes.",
    "- Counts above differ from AGENTS after regeneration.",
    "- This projection claims authority over live command output.",
  ];
  return lines.join("\n");
}

export async function runReadmeGenerator(argv: string[]): Promise<void> {
  const snapshot = snapshotFromAgents(await Deno.readTextFile(AGENTS));
  await Deno.writeTextFile(OUT, renderReadme(snapshot) + "\n");
  await formatGeneratedFile(OUT);
  const receipt = {
    type: "readme",
    position: "8/85",
    action: "generate",
    stable: argv.includes("--stable"),
    source_manifest_hash: snapshot.manifestHash,
    written: "src/x88E0_readme_bootstrap.myc.md",
  };
  console.log(JSON.stringify(receipt));
}

if (import.meta.main) await runReadmeGenerator(Deno.args);
