#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run
// src/x8900_coordinate_guide_gen.ts — coordinate guide generator
// position: 8/9 → cache(8) × penultimate(9) = projection of the naming key
// hex_dipole: "5F 00 00 00 40 00 00 33"
//   void_infinity+0.74 (PRIMARY: the coordinate ground itself; bucket 8 MATCH)
//   foundation_container+0.50 (reads the structured glossary registry)
//   completion_frontier+0.40 (emits a finished reference doc)
// placement_policy: axis
// maturity: active
// horizon: none (English projection of the glossary's bucket archetypes)
// skill_tag: coordinates
// skill_safe: yes-with-care
// intent: project the glossary's kind:03 bucket archetypes into an ENGLISH
//   coordinate reference, so a newcomer / new voice can decode xNNNN_ names
//   without the archived HUMAN palimpsest (the original informal Ukrainian key).
//
// The xNNNN_ naming scheme is the substrate's single most load-bearing
// convention, but its key lived only in the HUMAN palimpsest (Ukrainian). This generator
// reads the authoritative bilingual source — the glossary's `kind:03` archetype
// records (src/x0001_glossary.ndjson) — and emits docs/COORDINATES.md in English.
// Deterministic (no timestamp); regenerate with `deno task coordinates`.

import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.224.0/path/mod.ts";
import { formatGeneratedFile } from "./x0012_generated_format.ts";

const HERE = dirname(fromFileUrl(import.meta.url));
const ROOT = dirname(HERE);
const GLOSSARY = join(HERE, "x0001_glossary.ndjson");
const OUT = join(ROOT, "docs", "COORDINATES.md");

interface Archetype {
  coord: string; // "0".."F"
  en: string; // English archetype phrase
  octetAxis: number; // 0..7 (8..F are the second octave of 0..7)
}

/** Read the glossary's kind:03 records — the authoritative bucket archetypes. */
async function loadArchetypes(): Promise<Archetype[]> {
  const text = await Deno.readTextFile(GLOSSARY);
  const out: Archetype[] = [];
  for (const line of text.trim().split("\n")) {
    let r: Record<string, unknown>;
    try {
      r = JSON.parse(line);
    } catch {
      continue;
    }
    if (r["00"] !== "03") continue;
    const ten = r["10"];
    const en = ten && typeof ten === "object"
      ? String((ten as { en?: string }).en ?? "")
      : String(ten ?? "");
    out.push({
      coord: String(r["01"]).toUpperCase(),
      en,
      octetAxis: Number(r["12"]),
    });
  }
  return out.sort((a, b) => parseInt(a.coord, 16) - parseInt(b.coord, 16));
}

function render(arch: Archetype[]): string {
  const axisName = (n: number) =>
    arch.find((a) => a.coord === n.toString(16).toUpperCase())?.en ?? "?";
  const lines: string[] = [
    "<!-- AUTO-GENERATED by src/x8900_coordinate_guide_gen.ts — do not edit by hand. -->",
    "<!-- source: src/x0001_glossary.ndjson (kind:03 archetypes). Regenerate: `deno task coordinates`. -->",
    "",
    "# Coordinate guide — decoding `xNNNN_` names",
    "",
    "Every file in `src/` is named `x<NNNN>_<handle>.<ext>`, where `<NNNN>` is a",
    "four-hex **coordinate**. The first hex digit is the **bucket** (a semantic",
    "archetype); the rest sub-addresses within it. Identity is by *role/coordinate*",
    "— editing a file keeps its name, so `grep`/`diff`/`git` all keep working",
    "(unlike pure content-addressing). This is the English projection of the key;",
    "the original bilingual sketch is archived at `docs/archive/HUMAN_2026-05-19.md`; the glossary is canonical.",
    "",
    "## The 8 octet axes",
    "",
    "Buckets cycle through 8 axes; hex `8`–`F` are the **second octave** of `0`–`7`",
    "(`8`→`0`, `9`→`1`, `A`→`2`, … `F`→`7`).",
    "",
    "| Axis | Archetype |",
    "| :--: | :-------- |",
  ];
  for (let i = 0; i < 8; i++) lines.push(`| ${i} | ${axisName(i)} |`);
  lines.push(
    "",
    "## The 16 buckets",
    "",
    "| Bucket | Archetype | Octet axis |",
    "| :----: | :-------- | :--------: |",
  );
  for (const a of arch) lines.push(`| ${a.coord} | ${a.en} | ${a.octetAxis} |`);
  lines.push(
    "",
    "## Decoding an example",
    "",
    "`x2F30_fqdn_resolver.ts` → bucket **2** = _" + axisName(2) +
      "_ → an organ",
    "of reflection/mapping (it resolves a name to where it lives). `x7700_*` →",
    "bucket **7** = _" + axisName(7) +
      "_ (receipts: a closed cycle). `x0001` →",
    "bucket **0** = _" + axisName(0) +
      "_ (the glossary: the ground primitives).",
    "",
    "## Why this matters",
    "",
    "A coordinate is a **guess at where a thing belongs**, audited continuously:",
    "`t audit` checks each organ's `hex_dipole` header has its strongest axis on",
    "its bucket. So the names are not decoration — they are a checked claim about",
    "each file's role in the substrate.",
    "",
  );
  return lines.join("\n");
}

async function main() {
  const arch = await loadArchetypes();
  if (arch.length === 0) {
    console.error("no kind:03 archetypes found in glossary — aborting");
    Deno.exit(1);
  }
  await Deno.writeTextFile(OUT, render(arch) + "\n");
  await formatGeneratedFile(OUT);
  console.log(
    `[write] docs/COORDINATES.md (${arch.length} buckets from glossary kind:03)`,
  );
}

if (import.meta.main) await main();
