#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run
// src/x8F00_external_surfaces_gen.ts — external surfaces registry generator
// position: 8/F → void-infinity(8) × completion-edge(F) = final descriptions of all surfaces
// hex_dipole: "93 00 00 00 00 00 33 59"
//   void_infinity-1.09 (PRIMARY: indexes external ABI, src runtime caches, and compost)
//   completion_frontier+0.89 (boundary tracking across folders)
//   harmony_emergence+0.33 (systemic coherence)
// placement_policy: axis
// intent: scan external surfaces (root ABI, tooling ABI, contracts, schemas, docs, fixtures, probes, proposals, chords, src runtime caches, compost) and generate src/x8F88_external_surfaces.myc.md registry
// maturity: active
// horizon: none (external surfaces registry implemented)
// skill_tag: external-surfaces
// skill_safe: yes

import {
  dirname,
  fromFileUrl,
  join,
} from "https://deno.land/std@0.224.0/path/mod.ts";
import { formatGeneratedFile } from "./x0012_generated_format.ts";
import {
  collectExternalSurfaces,
  summarizeExternalSurfaces,
} from "./x8F10_external_surfaces_core.ts";

const HERE = dirname(fromFileUrl(import.meta.url));
const OUTPUT_PATH = join(HERE, "x8F88_external_surfaces.myc.md");

async function main() {
  const args = Deno.args;
  const wantJson = args.includes("--json");
  const wantVolatile = args.includes("--volatile");
  const stable = args.includes("--stable") || !wantVolatile;

  const entries = await collectExternalSurfaces({
    stable,
    includeVolatile: !stable,
  });

  const summary = summarizeExternalSurfaces(entries);

  if (wantJson) {
    const payload = {
      type: "external_surfaces",
      position: "8/F",
      summary,
      entries,
    };
    console.log(JSON.stringify(payload, null, 2));
    return;
  }

  const lines: string[] = [];
  lines.push(
    `<!-- AUTO-GENERATED by src/x8F00_external_surfaces_gen.ts — do not edit by hand. -->`,
  );
  if (!stable) {
    lines.push(`<!-- generated_at: ${new Date().toISOString()} -->`);
  }
  lines.push(``);
  lines.push(`# Substrate external surfaces registry`);
  lines.push(``);
  lines.push(
    `*Generated migration dashboard and index of all file-based interfaces, documents, and local caches outside the core Deno flat-src code base.*`,
  );
  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`| Category | File Count |`);
  lines.push(`| :--- | :---: |`);
  for (const [cat, count] of Object.entries(summary).sort()) {
    lines.push(`| ${cat.replace(/_/g, " ")} | ${count} |`);
  }
  lines.push(`| **Total** | **${entries.length}** |`);
  lines.push(``);
  lines.push(`## Registered Surfaces`);
  lines.push(``);

  if (!stable) {
    lines.push(
      `| Category | Surface | Canonical Status | Canonical Target | Next Action | Blocked By | Size (bytes) | Last Modified |`,
    );
    lines.push(
      `| :--- | :--- | :--- | :--- | :--- | :--- | :---: | :--- |`,
    );
    for (const e of entries) {
      lines.push(
        `| ${
          e.category.replace(/_/g, " ")
        } | [${e.surface}](../${e.surface}) | ${e.canonical_status} | ${e.canonical_target} | ${e.next_action} | ${e.blocked_by} | ${
          e.size ?? 0
        } | ${e.mtime ?? "unknown"} |`,
      );
    }
  } else {
    lines.push(
      `| Category | Surface | Canonical Status | Canonical Target | Next Action | Blocked By |`,
    );
    lines.push(
      `| :--- | :--- | :--- | :--- | :--- | :--- |`,
    );
    for (const e of entries) {
      lines.push(
        `| ${
          e.category.replace(/_/g, " ")
        } | [${e.surface}](../${e.surface}) | ${e.canonical_status} | ${e.canonical_target} | ${e.next_action} | ${e.blocked_by} |`,
      );
    }
  }
  lines.push(``);

  await Deno.writeTextFile(OUTPUT_PATH, lines.join("\n"));
  await formatGeneratedFile(OUTPUT_PATH);

  const receipt = {
    type: "external_surfaces_gen",
    position: "8/F",
    action: "generate",
    note: "external surfaces registry generated successfully",
    summary,
    total_surfaces: entries.length,
  };

  console.log(JSON.stringify(receipt, null, 2));
}

if (import.meta.main) {
  await main();
}
